
POST http://localhost:9000
content-type: application/application/xml

<ENVELOPE>
   <HEADER>
     <VERSION>1</VERSION>
     <TALLYREQUEST>Export</TALLYREQUEST>
     <TYPE>Collection</TYPE>
     <ID>Company Collection</ID>
   </HEADER>
   <BODY>
     <DESC>
       <STATICVARIABLES>
         <SVEXPORTFORMAT>$$SysName:UTF8JSON</SVEXPORTFORMAT>
         <SVExportLanguage>$$SysName:UTF8JSON</SVExportLanguage>
       </STATICVARIABLES>
       <TDL>
         <TDLMESSAGE>
           <COLLECTION NAME="Company Collection" ISMODIFY="No" ISFIXED="No" ISINITIALIZE="No" ISOPTION="No" ISINTERNAL="No">
             <TYPE>StockItem</TYPE>
             <BELONGSTO>Yes</BELONGSTO>
             <FETCH>*</FETCH>
           </COLLECTION>
         </TDLMESSAGE>
       </TDL>
     </DESC>
   </BODY>
</ENVELOPE>