###Get for as is data
GET http://localhost:7016/api/{{ksSample}}

###Get for data from json file as array only
GET http://localhost:7016/api/{{ksSample}}/DataOnly

###Get for data transformed to Modal data
GET http://localhost:7016/api/{{ksSample}}/FromModal

###Get for data transformed to Modal data and Uuid also
GET http://localhost:7016/api/{{ksSample}}/FromModalUuid

###Get for data transformed to Modal data , Uuid and timeStamp also
GET http://localhost:7016/api/{{ksSample}}/FromModalUuidAndTS

###

POST http://localhost:7016/api/ksSample/BodyCheck
content-type: application/json

###

POST http://localhost:7016/api/{{ksSample}}
content-type: application/json

{

}

###

POST http://localhost:7016/api/{{ksSample}}/FromModal
content-type: application/json

{

}

###

POST http://localhost:7016/api/{{ksSample}}/Upload
content-type: application/json

[

]

###

POST http://localhost:7016/api/{{ksSample}}/UploadFromModal
content-type: application/json

[

]