###Get for as is data
GET http://localhost:7016/src/ksSample

###Get for data from json file as array only
GET http://localhost:7016/src/ksSample/DataOnly

###Get for data transformed to Modal data
GET http://localhost:7016/src/ksSample/FromModal

###Get for data transformed to Modal data and Uuid also
GET http://localhost:7016/src/kssample/FromModalUuid

###Get for data transformed to Modal data , Uuid and timeStamp also
GET http://localhost:7016/src/kssample/FromModalUuidAndTS

###

POST http://localhost:7016/src/ksSample/BodyCheck
content-type: application/json

###

POST http://localhost:7016/src/kssample
content-type: application/json

{

}

###

POST http://localhost:7016/src/kssample/FromModal
content-type: application/json

{

}

###

POST http://localhost:7016/src/kssample/Upload
content-type: application/json

[

]

###

POST http://localhost:7016/src/kssample/UploadFromModal
content-type: application/json

[

]