###Get for as is data
GET http://localhost:7016/src/kssample


###Get for data transformed to Modal data
GET http://localhost:7016/src/ksSample/FromModal


###Get for data transformed to Modal data and Uuid also
GET http://localhost:7016/src/kssample/FromModalUuid


###Get for data transformed to Modal data , Uuid and timeStamp also
GET http://localhost:7016/src/kssample/FromModalUuidAndTS

###Get for data from json file as array only
GET http://localhost:7016/src/ksSample/DataOnly

###Get for as is data
GET http://localhost:7016/src/ksSample/1