POST http://localhost:7016/src/ksSample/BodyCheck
content-type: application/json

###
POST http://localhost:7016/src/ksSample
content-type: application/json

{
"Name":"Ram",
"ContactNumber":536281927
}

### GetSelectColumns
POST http://localhost:7016/src/ksSample/GetSelectColumns
content-type: application/json

{

}

### Upload
POST http://localhost:7016/src/ksSample/Upload
content-type: application/json

[{
"nmae":"kkk",
"contactNumber":89898
},
{
"nmae":"ppp",
"contactNumber":7777
},
{
"nmae":"mmmm",
"contactNumber":5555
}]

### UploadFromModal
POST http://localhost:7016/src/ksSample/UploadFromModal
content-type: application/json

[{
"Name":"aaaaaaaaa",
"Mobile":89898
},
{
"Name":"bbb",
"contactNumber":7777
},
{
"nmae":"ccccccc",
"Mobile":5555
}]